# report.py — legacy entry point (kept for reference)
# Text reports are now generated by core/reporter.py → save_text_report()
# Run: python main.py

import subprocess, sys
subprocess.run([sys.executable, "main.py"] + sys.argv[1:])
